name: OCaml CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up OCaml
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-compiler: '4.12.0'
    - name: Install dependencies
      run: opam install . --deps-only --with-test
    - name: Build
      run: dune build
    - name: Run tests
      run: dune runtest